### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by dgastudio** [okonet/react-scroll-sync#91]
nextjs : 13.5.6
lib: ^0.11.0

ReferenceError: Element is not defined
at Object.<anonymous> (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:854:71)
    at __webpack_require__ (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:30:30)
    at Object.<anonymous> (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:883:23)
        at __webpack_require__ (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:30:30)
        at /Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:76:18
        at /Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:79:10
        at webpackUniversalModuleDefinition (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:3:20)
        at Object.<anonymous> (/Users/****/v3/frontend_next/node_modules/react-scroll-sync/dist/index.js:10:3)
            at Module._compile (node:internal/modules/cjs/loader:1233:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
            at Module.load (node:internal/modules/cjs/loader:1091:32)
            at Module._load (node:internal/modules/cjs/loader:938:12)
            at Module.require (node:internal/modules/cjs/loader:1115:19)
            at mod.require (/Users/****/v3/frontend_next/node_modules/next/dist/server/require-hook.js:64:28)
            at require (node:internal/modules/helpers:119:18) {

i can't inderstand the issue

**Comment by okonet** [comment]
I'm not offering free debugging session, unfortunately. If you're still interested in my help, I can send you a calendly link to pick the time for the paid session.

**Comment by dev-m-work** [comment]
I have the same issue after updating the packages

**Comment by dev-m-work** [comment]
> I have the same issue after updating the packages

Please send it so we can debug your package please

**Comment by DusanStojanovic-gowago** [comment]
The same error happened to me after upgrading from `0.11.0` to `0.11.11`. 

Next.js: 14.0.0.

This PR must be the culprit: https://github.com/okonet/react-scroll-sync/pull/90

**Comment by okonet** [comment]
Feel free to investigate and create a PR.

**Comment by AmelloAster** [comment]
I have same issuse, the package version is 0.11.1, when i use this version in ssr framework, I will get this problem

**Comment by DRoet** [comment]
Fixed in 0.11.2
